No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Soda_VA_BOT\soda_va_bot.py", line 475, in button
    eval(s_path.menu_buttons[query.data])
  File "<string>", line 1, in <module>
  File "C:\Soda_VA_BOT\soda_va_bot.py", line 358, in vpn_menu
    download = ((read_db_cell("download", 'bytes', filename=s_con_path) * 8) /
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Soda_VA_BOT\s_handle_db.py", line 7, in read_db_cell
    data = json.load(f)
           ^^^^^^^^^^^^
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Soda_VA_BOT\soda_va_bot.py", line 475, in button
    eval(s_path.menu_buttons[query.data])
  File "<string>", line 1, in <module>
  File "C:\Soda_VA_BOT\soda_va_bot.py", line 358, in vpn_menu
    download = ((read_db_cell("download", 'bytes', filename=s_con_path) * 8) /
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Soda_VA_BOT\s_handle_db.py", line 7, in read_db_cell
    data = json.load(f)
           ^^^^^^^^^^^^
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Soda_VA_BOT\soda_va_bot.py", line 475, in button
    eval(s_path.menu_buttons[query.data])
  File "<string>", line 1, in <module>
  File "C:\Soda_VA_BOT\soda_va_bot.py", line 358, in vpn_menu
    download = ((read_db_cell("download", 'bytes', filename=s_con_path) * 8) /
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Soda_VA_BOT\s_handle_db.py", line 7, in read_db_cell
    data = json.load(f)
           ^^^^^^^^^^^^
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\karelikov\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
